stages:
- test
- name: deploy
  if: tag IS present

language: c
os: linux
dist: trusty

install:
- scripts/install

script:
- scripts/build --test
- scripts/test

.deploy_job_template: &deploy_job_template
  script:
  - scripts/build
  - tar -czf flora-${TRAVIS_TAG}-$(uname)-$(uname -m).tar.gz -C out ./usr
  deploy:
    provider: releases
    api_key:
      secure: coEAT1LELM2cfXxMUwMcbVbfnNS7fXZgGpQ7V+GheO87tnKSfcIgXfnXwjxlJWpVnmyuTU75VlmcTVmf1bIUCaOLD1VGjR4fFZLeuRXxt5+ikMwgZ5t62j967K0Zmg/2KIL4VBjLFAfVqJnk6apByw+M/YgMHf9glRUzMgSLa7LvKTWCYzHtYsNlqGNLHlF4Oi0gS4lsAP+PcFFsO0om5FaSHoQq1ijRrNt5e06rX6X4pohNYHlR32iwSWDUU7Ergjkb0VD4tJh20qvGbRMq5WD45T1dV/8CsVZQvTlpjEaw/Vvlaw8ySSmKCXsj7Wi+H0pTqaARMkY+a45cUq9BwNRQpCr9pZ72fxbYPomNVWO7lYPQwcD/H61XsoIXwiu+djM4XYB+l1GlS7xWnTME9pyS+i7NDa7Y9zjRRsaY5eHiLNQqK/gTm91hQIWf2+jZeyQyro2Vd01kVU9rYa5Se2nVqYqAOxncOg8ovDoMf8mfOaL++dkgVpdcUXLOhcBA1MxoNG1zhZzB/5dnJ90G7mUM+qtRYtqiVs7OGLfZJRTwZxOPYe5wiWCck8sTtZMvqZ4RYvsnmLrOth3fmtw7doIEmpic47MLdnndRqTEvch6a6InXAaPAFine4IybYFjXkK2VUCTc4TZ5VEbggab4myr/mfPmO9bgPFEZ09PNAo=
    file_glob: true
    skip_cleanup: true
    file: "./flora-*.tar.gz"
    on:
      repo: yodaos-project/flora
      tags: true

jobs:
  include:
  - stage: test
    os: linux
  - stage: test
    os: osx

  - stage: deploy
    <<: *deploy_job_template
    os: linux
  - stage: deploy
    <<: *deploy_job_template
    os: osx
